> This is one of the 100 recipes of the [IPython Cookbook](http://ipython-books.github.io/), the definitive guide to high-performance scientific computing and data science in Python.


# 1.3. Introducing the multidimensional array in NumPy for fast array computations

1. Let's import the built-in `random` Python module and NumPy.

In [1]:
import random
import numpy as np

We use the `%precision` magic (defined in IPython) to show only 3 decimals in the Python output. This is just to alleviate the text.

In [2]:
%precision 3

'%.3f'

2. We generate two Python lists `x` and `y`, each one containing one million random numbers between 0 and 1.

In [3]:
n = 1000000
x = [random.random() for _ in range(n)]
y = [random.random() for _ in range(n)]

In [4]:
x[:3], y[:3]

([0.173, 0.493, 0.698], [0.069, 0.501, 0.091])

3. Let's compute the element-wise sum of all these numbers: the first element of `x` plus the first element of `y`, and so on. We use a `for` loop in a list comprehension.

In [5]:
z = [x[i] + y[i] for i in range(n)]
z[:3]

[0.242, 0.994, 0.790]

4. How long does this computation take? IPython defines a handy `%timeit` magic command to quickly evaluate the time taken by a single command.

In [6]:
%timeit [x[i] + y[i] for i in range(n)]

10 loops, best of 3: 163 ms per loop


5. Now, we will perform the same operation with NumPy. NumPy works on multidimensional arrays, so we need to convert our lists to arrays. The `np.array()` function does just that.

In [7]:
xa = np.array(x)
ya = np.array(y)

In [8]:
xa[:3]

array([ 0.173,  0.493,  0.698])

The arrays `xa` and `ya` contain the *exact* same numbers than our original lists `x` and `y`. Whereas those lists where instances of a built-in class `list`, our arrays are instances of a NumPy class `ndarray`. Those types are implemented very differently in Python and NumPy. We will see that, in this example, using arrays instead of lists leads to drastic performance improvements.

6. Now, to compute the element-wise sum of these arrays, we don't need to do a `for` loop anymore. In NumPy, adding two arrays means adding the elements of the arrays component by component.

In [9]:
za = xa + ya
za[:3]

array([ 0.242,  0.994,  0.79 ])

We see that the list `z` and the array `za` contain the same elements (the sum of the numbers in `x` and `y`).

7. Let's compare the performance of this NumPy operation with the native Python loop.

In [10]:
%timeit xa + ya

The slowest run took 5.83 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 3: 927 µs per loop


We observe that this operation is more than one order of magnitude faster in NumPy than in pure Python!

8. Now, we will compute something else: the sum of all elements in `x` or `xa`. Although this is not an element-wise operation, NumPy is still highly efficient here. The pure Python version uses the built-in `sum` function on an iterable. The NumPy version uses the `np.sum()` function on a NumPy array.

In [11]:
%timeit sum(x)  # pure Python
%timeit np.sum(xa)  # NumPy

100 loops, best of 3: 5.56 ms per loop
The slowest run took 5.43 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 3: 412 µs per loop


We also observe an impressive speedup here.

9. Finally, let's perform a last operation: computing the arithmetic distance between any pair of numbers in our two lists (we only consider the first 1000 elements to keep computing times reasonable). First, we implement this in pure Python with two nested `for` loops.

In [12]:
d = [abs(x[i] - y[j]) 
     for i in range(1000) for j in range(1000)]

In [13]:
d[:3]

[0.104, 0.328, 0.081]

10. Now, we use a NumPy implementation, bringing out two slightly more advanced notions. First, we consider a **two-dimensional array** (or matrix). This is how we deal with *two* indices *i* and *j*. Second, we use **broadcasting** to perform an operation between a 2D array and a 1D array. We will give more details in *How it works...*

In [17]:
da = np.abs(xa[:1000,None] - ya[:1000])

In [18]:
da.shape

(1000, 1000)

In [19]:
%timeit [abs(x[i] - y[j]) for i in range(1000) for j in range(1000)]
%timeit np.abs(xa[:1000, None] - ya[:1000])

1 loop, best of 3: 199 ms per loop
100 loops, best of 3: 3.14 ms per loop


Here again, observe observe the significant speedups.

> You'll find all the explanations, figures, references, and much more in the book (to be released later this summer).

> [IPython Cookbook](http://ipython-books.github.io/), by [Cyrille Rossant](http://cyrille.rossant.net), Packt Publishing, 2014 (500 pages).

broad cast

In [38]:
A = np.random.randn(3,2)
B = np.random.randn(2)

In [39]:
A + B

array([[ 0.62 ,  1.405],
       [ 2.25 ,  1.861],
       [-0.103,  2.847]])

means

In [40]:
A + B.reshape(1,2)

array([[ 0.62 ,  1.405],
       [ 2.25 ,  1.861],
       [-0.103,  2.847]])

example

In [70]:
A = np.random.randint(10, size=5)
B = np.random.randint(10, size=5)
print('A', A)
print('B', B)

A [2 2 1 0 0]
B [7 9 0 2 2]


In [72]:
A[:, None].shape

(5, 1)

In [74]:
B.reshape(-1,5).shape

(1, 5)

https://deepage.net/features/numpy-broadcasting.html